<x-app-layout>
<x-slot name="header"><h2 class="text-fuchsia-300 text-3xl font-semibold tracking-tight">Challenge Form</h2></x-slot>
<form method="POST" action="{{ $challenge->exists ? route('prop-challenges.update',$challenge) : route('prop-challenges.store') }}" class="bg-slate-900/90 border border-fuchsia-900/40 rounded-2xl p-6 text-slate-200 space-y-4 shadow-xl shadow-fuchsia-950/20">
@csrf @if($challenge->exists) @method('PUT') @endif
<div><label class="text-sm text-slate-400">Trading Account (Opsional)</label><select name="trading_account_id" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5"><option value="">Tidak ditautkan</option>@foreach($accounts as $acc)<option value="{{ $acc->id }}" @selected((string)old('trading_account_id',$challenge->trading_account_id)===(string)$acc->id)>{{ $acc->name }}</option>@endforeach</select></div>
<div><label class="text-sm text-slate-400">Prop Firm</label><input name="prop_firm_name" value="{{ old('prop_firm_name',$challenge->prop_firm_name) }}" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5" placeholder="Contoh: FTMO" required></div>
<div><label class="text-sm text-slate-400">Account Type</label><input name="account_type" value="{{ old('account_type',$challenge->account_type) }}" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5" placeholder="Contoh: 10K Challenge" required></div>
<div class="grid md:grid-cols-2 gap-3">
<div><label class="text-sm text-slate-400">Initial Balance (USD)</label><input name="initial_balance" type="number" step="0.01" value="{{ old('initial_balance',$challenge->initial_balance) }}" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5" required><p class="text-xs text-slate-500 mt-1">Modal awal challenge.</p></div>
<div><label class="text-sm text-slate-400">Profit Target (USD)</label><input name="profit_target" type="number" step="0.01" value="{{ old('profit_target',$challenge->profit_target) }}" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5" required><p class="text-xs text-slate-500 mt-1">Target profit agar status lulus.</p></div>
<div><label class="text-sm text-slate-400">Daily Drawdown Limit (USD)</label><input name="daily_drawdown" type="number" step="0.01" value="{{ old('daily_drawdown',$challenge->daily_drawdown) }}" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5" required></div>
<div><label class="text-sm text-slate-400">Max Drawdown Limit (USD)</label><input name="max_drawdown" type="number" step="0.01" value="{{ old('max_drawdown',$challenge->max_drawdown) }}" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5" required></div>
<div><label class="text-sm text-slate-400">Minimum Trading Days</label><input name="minimum_trading_days" type="number" value="{{ old('minimum_trading_days',$challenge->minimum_trading_days ?? 5) }}" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5" required></div>
<div><label class="text-sm text-slate-400">Current Balance (USD)</label><input name="current_balance" type="number" step="0.01" value="{{ old('current_balance',$challenge->current_balance ?? 0) }}" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5" required><p class="text-xs text-slate-500 mt-1">Update manual berdasarkan dashboard prop firm.</p></div>
</div>
<div><label class="text-sm text-slate-400">Challenge Status</label><select name="challenge_status" class="w-full mt-1 bg-slate-950 border border-slate-700 rounded-lg p-2.5"><option value="ongoing" @selected(old('challenge_status',$challenge->challenge_status)==='ongoing')>ongoing</option><option value="passed" @selected(old('challenge_status',$challenge->challenge_status)==='passed')>passed</option><option value="failed" @selected(old('challenge_status',$challenge->challenge_status)==='failed')>failed</option></select></div>
@if($errors->any())<div class="text-rose-400 text-sm">{{ $errors->first() }}</div>@endif
<button class="bg-fuchsia-400 px-4 py-2 rounded-lg text-slate-950 shadow-[0_0_18px_rgba(232,121,249,.35)]">Save Challenge</button>
</form>
</x-app-layout>
